[tool.poetry]
name = "python_repository_simple"
version = "0.0.0"
description = "python_repository_simple"
authors = ["yamap55"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
# lint
flake8 = "4.0.1"
black = "22.3.0"
flake8-docstrings = "1.6.0"
flake8-quotes = "3.3.1"
flake8-bugbear = "22.4.25"

# test
pytest = "7.1.2"
pytest-cov = "3.0.0"

# notebook
ipykernel = "6.13.0"

[tool.pytest.ini_options]
junit_family = "xunit1"
addopts = "--verbose --cov --showlocals --durations=5"

[tool.coverage.run]
omit = ["*/tests/*", "*/site-packages/*"]
