name: ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: ./.github/actions/python_setup
      - name: set up poetry
        uses: ./.github/actions/poetry_setup
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.6
      - name: run analyze(use reviewdog)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -conf=./.github/actions/ruff.yml -reporter=github-check -filter-mode=nofilter -fail-on-error
